name: 'Alfredo Llanos'
description: 'Web development. HTML5, Javascript, CSS3, PHP.'
url: 'http://tsoho.es/a'
baseurl: 'http://biojazzard.github.io/_site'
#baseurl: 'http://localhost/dropbox/tallerdelsoho.es/alfredo.llanos/_site'
#baseurl: ''

markdown: redcarpet
highlighter: pygments
permalink: /:title/
exclude: [
  'node_modules',
  'bower_components',
  'Gruntfile.js',
  'package.json',
  'bower.json',
  'requirements.txt',
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'css',
  'sass',
  'js',
  'coffee',
  'env',
  'tmp'
]

assets:
  root_url: '/assets'

images:
  root_url: '/assets/img'

disqus:
  shortname: 'biojazzard'
